# Generated by Django 4.2.7 on 2024-01-05 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='image/patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_hsn', models.PositiveIntegerField(null=True)),
                ('item_unit', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_taxable', models.CharField(max_length=255)),
                ('item_gst', models.CharField(max_length=255, null=True)),
                ('item_igst', models.CharField(max_length=255, null=True)),
                ('item_sale_price', models.PositiveIntegerField()),
                ('item_current_stock', models.PositiveBigIntegerField(default=0)),
                ('item_purchase_price', models.PositiveBigIntegerField()),
                ('item_stock_in_hand', models.PositiveBigIntegerField(default=0)),
                ('item_at_price', models.PositiveBigIntegerField(default=0)),
                ('item_date', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('gstin', models.CharField(max_length=16)),
                ('gst_type', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('to_pay', models.BooleanField(null=True)),
                ('to_recieve', models.BooleanField(null=True)),
                ('date', models.DateField(null=True)),
                ('last_updated_by', models.CharField(default='', max_length=255)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/staff')),
                ('position', models.CharField(blank=True, default='staff', max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.PositiveIntegerField()),
                ('bill_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.PositiveIntegerField()),
                ('cgst', models.PositiveIntegerField()),
                ('sgst', models.PositiveIntegerField()),
                ('tax_amount', models.PositiveIntegerField()),
                ('adjustment', models.PositiveIntegerField()),
                ('supply_source', models.CharField(max_length=150, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.parties')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
            ],
        ),
        migrations.AddField(
            model_name='parties',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
