# Generated by Django 4.2.7 on 2024-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='grand_total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
