# Generated by Django 4.2.7 on 2024-01-09 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillSoftwareapp', '0002_purchasebill_grand_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parties',
            old_name='to_recieve',
            new_name='to_receive',
        ),
        migrations.RenameField(
            model_name='purchasebill',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='item',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='address',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='igst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='paidoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_method',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='totalbalance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='cgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='sgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hsn', models.IntegerField()),
                ('tax', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasebill')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
    ]
