# Generated by Django 4.2.7 on 2024-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0004_alter_purchasebill_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='adjustment',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='tax_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
