# Generated by Django 4.2.7 on 2024-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0005_alter_purchasebill_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='paidoff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='totalbalance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
