# Generated by Django 4.2.7 on 2024-01-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0007_purchasebill_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
