# Generated by Django 4.2.7 on 2024-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0008_alter_purchasebill_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_purchase_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
