# Generated by Django 4.2.7 on 2024-01-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0009_alter_itemmodel_item_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebillitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
