# Generated by Django 4.2.7 on 2024-01-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0010_alter_purchasebillitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
