# Generated by Django 4.2.7 on 2024-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0011_itemmodel_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='tax',
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='item_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
