# Generated by Django 4.2.7 on 2024-01-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0013_alter_purchasebillitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='adjustment',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='cgst',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='grand_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='igst',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='sgst',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='subtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='tax_amount',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='PurchaseBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('purchasebill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasebill')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
    ]
