# Generated by Django 4.2.7 on 2024-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0014_alter_purchasebill_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_sale_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
