# Generated by Django 4.2.7 on 2024-01-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0015_alter_itemmodel_item_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_date',
            field=models.DateField(null=True),
        ),
    ]
