# Generated by Django 4.2.7 on 2024-01-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0016_alter_itemmodel_item_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='item_name',
        ),
    ]
