# Generated by Django 4.2.7 on 2024-01-24 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillSoftwareapp', '0018_rename_created_by_parties_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('gstin', models.CharField(max_length=16)),
                ('gst_type', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('to_pay', models.BooleanField(null=True)),
                ('to_receive', models.BooleanField(null=True)),
                ('date', models.DateField(null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_by', models.CharField(default=0, max_length=255)),
                ('current_date', models.DateField(blank=True, max_length=255, null=True)),
                ('End_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasebillhistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchasebillhistory',
            name='purchasebill',
        ),
        migrations.RemoveField(
            model_name='purchasebillhistory',
            name='staff',
        ),
        migrations.RenameField(
            model_name='purchasebill',
            old_name='bill_date',
            new_name='billdate',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='paidoff',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='supply_source',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='totalbalance',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='staff',
        ),
        migrations.AddField(
            model_name='company',
            name='End_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='start_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='adjust',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='advance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='billno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='cheque_no',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='grandtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='pay_method',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplyplace',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='taxamount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tot_bill_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='upi_no',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='purchasebill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasebill'),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='cgst',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='igst',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='sgst',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='subtotal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebillitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company'),
        ),
        migrations.AlterField(
            model_name='purchasebillitem',
            name='discount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebillitem',
            name='tax',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Parties',
        ),
        migrations.DeleteModel(
            name='PurchaseBillHistory',
        ),
        migrations.AddField(
            model_name='purchasebilltransactionhistory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company'),
        ),
        migrations.AddField(
            model_name='purchasebilltransactionhistory',
            name='purchasebill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasebill'),
        ),
        migrations.AddField(
            model_name='purchasebilltransactionhistory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
        migrations.AddField(
            model_name='party',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company'),
        ),
        migrations.AddField(
            model_name='party',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
        migrations.AddField(
            model_name='party',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.party'),
        ),
    ]
